legit_domains:                          # Own or legitimate (sub)domains, different to foreign domains that are fp
- legitdomain1.de
- legitdomain2.de

falsepositives: 
- false-positive1.de                    # Explaination of FP
- false-positive1.de                    # Explaination of FP

levenshtein_score: 25

check_website_content: true             # True or false, switch to allow or disallow contacting and checking the suspicious website, note potential problems with opsec
check_VT: true                          # True or false, switch to check the suspicious domain against vt and enrich the alert with informations
check_phishing_domainname: true         # True or false, switch to allow or disallow checking the domain for suspicious phishing keywords

content_keywords:                       # Example keywords to check the websites content with to make sure it replicates your own website
- contentkeyword1
- contentkeyword2

VT_API_Key: ""                          # VT API Key needed if 'check_VT' is set to true

phishing_keywords:                      # Example list of pot phishing keywords (german/english)
- bund
- cert
- admin
- monitor
- config
- konfig
- support
- unterst체tzung
- unterstuetzung
- update
- aktualisieren
- login
- reward
- secure
- sicher
- auth
- verify
- account
- konto
- exchange
- service
- ticket
- customer
- kunde
- mail
- manage
- portal
- cloud
- reset
- notification
- benachrichtigung
- alert
- alarm
- confirm
- best채tig
- bestaetig
- access
- zugriff
- zugang
- user
- person
- benutzer
- nutzer
- profil
- settings
- einstellung
- privacy
- data
- backup
- download
- upload
- file
- recovery
- wiederherstellung
- encrypt
- verschl체sselt
- verschluesselt
- ssl
- vpn
- endpoint
- server
- dashboard
- control
- tech
- software
- hardware
- installation
- guide
- documentation
- api
- integration
- dev
- entwickler
- entwicklung
- project
- projekt
- repo
- version
- release
- patch
- bugfix
- feedback
- survey
- befragung
- umfrage
- review
- forum
- discussion
- diskussion
- blog
- news
- announcement
- event
- webinar
- tutorial
- training
- zertifikat
- zertifizierung
- demo
- trial
- offer
- angebot
- discount
- sale
- subscribe
- registration
- registrierung
- member
- mitglied
- partner
- affiliate
- testimonial
- resource
- faq
- contact
- kontakt
- career
- karriere
- job
- application
- anwendung
- interview
- employee
- mitarbeiter
- team
- work
- arbeit
- collaboration
- meeting
- schedule
- calendar
- kalendar
- task
- aufgabe
- reminder
- erinnerung
- message
- chat
- communication
- kommunikation
- social
- network
- community
- help
- advice
- strategy
- policy
- compliance
- security
- warning
- warnung
- protection
- schutz
- safe
- consulting
- programming
- innovation
- beta
- launch
- upgrade
- maintain
- wartung
- warten
- status
- report
- issue
- bug
- fix
- edition
- license
- agreement
- terms
- copyright
- legal
- notice
- knowledgebase
- video
- workshop
- seminar
- conference
- konferenz
- hackathon
- challenge
- prize
- preis
- giveaway
- contest
- analys
- statistic
- trend
- insight
- newsletter
- broadcast
- live
- presentation
- photo
- gallery
- illustration
- game
- app
- tool
- platform
- system
- solution
- product
- feature
- benefit
- vorteil
- angebot
- advantage
- preview
- teaser
- highlight
- portfolio
- catalog
- katalog
- brochure
- flyer
- poster
- advertise
- werbung
- logo
- slogan
- leadership
- f체hrung
- fuehrung
- management
- partners
- park
- menu
- beta